jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ${{ github.workspace }}/.gradle/minecraft

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Setup decompiled workspace
      run: ./gradlew setupDecompWorkspace
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Archive artifacts for build
      uses: actions/upload-artifact@v2
      with:
        name: Sponge Jars
        path: '${{ github.workspace }}/SpongeAPI/build/libs/*.jar

          ${{ github.workspace }}/build/libs/*.jar

          '
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___build-project.yaml
