jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: run number with offset
      run: echo "BUILD_NUMBER=$(($GITHUB_RUN_NUMBER+4082))" >> $GITHUB_ENV
    - continue-on-error: true
      name: Setup workspace
      run: 'echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV

        echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

        ./gradlew --refresh-dependencies clean setupDecompWorkspace

        '
    - continue-on-error: true
      env:
        CI_SYSTEM: Github Actions
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        ORG_GRADLE_PROJECT_spongePassword: ${{ secrets.SPONGE_MAVEN_REPO_PASSWORD
          }}
        ORG_GRADLE_PROJECT_spongeReleaseRepo: ${{ secrets.SPONGE_MAVEN_RELEASE_REPO_URL
          }}
        ORG_GRADLE_PROJECT_spongeSnapshotRepo: ${{ secrets.SPONGE_MAVEN_SNAPSHOT_REPO_URL
          }}
        ORG_GRADLE_PROJECT_spongeUsername: ${{ secrets.SPONGE_MAVEN_REPO_USER }}
      name: Publish to Sponge Maven & GitHub Packages
      run: ./gradlew -s clean build :uploadArchives
    - continue-on-error: true
      name: Add artifacts to build
      uses: actions/upload-artifact@v2
      with:
        name: Sponge Jars
        path: '${{ github.workspace }}/SpongeCommon/SpongeAPI/build/libs/*.jar

          ${{ github.workspace }}/SpongeCommon/build/libs/*.jar

          ${{ github.workspace }}/build/libs/*.jar

          '
    - continue-on-error: true
      name: Production Ready Jar
      uses: actions/upload-artifact@v2
      with:
        name: Sponge Production Jar
        path: ${{ github.workspace }}/build/libs/*RC${{ env.BUILD_NUMBER }}.jar
name: Build and Deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yaml
